# Generated by Django 5.1 on 2026-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manim', '0005_code_share_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='share_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
