# Generated by Django 5.1 on 2026-06-02 11:02

import manim.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manim', '0006_code_is_public_alter_code_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='share_id',
            field=models.CharField(blank=True, default=manim.models.generate_share_id, max_length=32, null=True, unique=True),
        ),
    ]
